name: Hosted Execution sans Docker Image

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  retain-files:
    name: Get test files and dependencies
    runs-on: ubuntu-latest
    #container: saucelabs/saucectl:latest
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      SAUCE_REGION: us-west-1
    steps:
      - uses: actions/checkout@v2
      # - name: Install dependencies
      #   run: |
      #     cd webdriverio/webdriver/best-practices
      #     npm ci
      - name: Install Saucectl
        run: npm install -g saucectl
      - name: Archive test files
        run: zip -r files.zip ./webdriverio/webdriver/best-practices
      - name: Push artifacts to Sauce Storage
        run: saucectl storage upload files.zip &> sauce-storage-output.log
      # This is hacky. Would be good to have this built into sauce storage
      - name: Parse storage ID from sauce-storage-output.log
        run: |
          echo "ARTIFACT_ID=$(cat sauce-storage-output.log | grep -oP 'The ID of your file is \K.*'" >> $GITHUB_ENV
      - name: Confirm ARTIFACT_ID is correct
        run: echo ${{ env.ARTIFACT_ID }}


  # run-tests:
  #   name: Run Tests in Sauce Labs hosted execution environment
  #   needs: retain-files
  #   runs-on: ubuntu-latest
  #   container: saucelabs/saucectl:latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       entrypoint: [
  #         "sh -c '
  #           wget $TEST_FILES;\
  #           npm ci;\
  #           npm run test.saucelabs.us;\
  #           curl \
  #             -H 'Accept: application/vnd.github+json' \
  #             -H 'Authorization: Bearer $GITHUB_TOKEN' \
  #             -H 'X-GitHub-Api-Version: 2022-11-28' \
  #             https://api.github.com/repos/dpgraham/demo-js/actions/artifacts/ARTIFACT_ID/ARCHIVE_FORMAT; \
  #         '",
  #       ]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: echo $GITHUB_TOKEN
  #     - name: Download test files
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: test-files
  #         path: webdriverio/webdriver/best-practices
  #     - name: List test files
  #       run: ls -la webdriverio/webdriver/best-practices

