name: Hosted Execution

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  push_to_registry:
    name: Get test files and dependencies
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tags }}
      label: ${{ steps.meta.outputs.labels }}
    steps:
      - uses: actions/checkout@v2
      # - name: Install dependencies
      #   run: |
      #     cd webdriverio/webdriver/best-practices
      #     npm ci
      - name: Retain artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-files
          path: webdriverio/webdriver/best-practices

  run-tests:
    name: Run Tests in Sauce Labs hosted execution environment
    needs: push_to_registry
    runs-on: ubuntu-latest
    container: saucelabs/saucectl:latest
    strategy:
      fail-fast: false
      matrix:
        entrypoint: [
          "sh -c '
            wget $TEST_FILES;\
            npm ci;\
            npm run test.saucelabs.us;\
          '",
        ]
    steps:
    - uses: actions/checkout@v2
    - name: Run Saucectl
      run:
        - echo "PLACEHOLDER"
        - echo ${{ matrix.entrypoint }}

