name: Best Practices Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # Build the project as a Docker image and push it to Docker Hub
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.output-tags.tags }}
      label: ${{ steps.meta.outputs.labels }}
      hello: World
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/js-hosted-execution
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Save Tags to Outputs
        id: output-tags
        run: echo "tags=${{ steps.meta.outputs.tags }}" >> $GITHUB_OUTPUT

  # Now run the tests. When Hosted Executor is ready, this should run a saucectl command to run
  # the tests from the previously created Docker image in the cloud
  run-tests:
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        DOCKER_TAG: ${{ needs.push_to_registry.outputs.tag }}
      run: |
        echo ${{ needs.push_to_registry.outputs.tag }}
        echo ${{ needs.push_to_registry.outputs.label }}
        echo ${{ needs.push_to_registry.outputs.hello }}
        echo "TODO: run saucectl with Docker container ${{ secrets.DOCKER_USERNAME }}/js-hosted-execution:$DOCKER_TAG"
