name: Hosted Execution sans Docker Image

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  retain-files:
    name: Get test files and dependencies
    runs-on: ubuntu-latest
    #container: saucelabs/saucectl:latest
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      SAUCE_REGION: us-west-1
    outputs:
      storage_id: ${{ env.STORAGE_ID }}
    steps:
      - uses: actions/checkout@v2
      # - name: Install dependencies
      #   run: |
      #     cd webdriverio/webdriver/best-practices
      #     npm ci
      - name: Install Saucectl
        run: npm install -g saucectl
      - name: Archive test files
        run: zip -r files.zip ./webdriverio/webdriver/best-practices
      - name: Push artifacts to Sauce Storage
        run: saucectl storage upload files.zip &> sauce-storage-output.log
      # This is hacky. Would be good to have this built into sauce storage
      - name: Parse storage ID from sauce-storage-output.log
        run: |
          cat sauce-storage-output.log
          echo "STORAGE_ID=$(cat sauce-storage-output.log | grep -oP 'The ID of your file is \K.*')" >> $GITHUB_ENV
      - name: Confirm STORAGE_ID is correct
        env:
          STORAGE_ID: ${{ env.STORAGE_ID }}
        run: |
          curl -u $SAUCE_USERNAME:$SAUCE_ACCESS_KEY https://api.$SAUCE_REGION.saucelabs.com/v1/storage/download/$STORAGE_ID --output test-files.zip
          ls -la


  run-tests:
    name: Run Tests in Sauce Labs hosted execution environment
    needs: retain-files
    runs-on: ubuntu-latest
    container: saucelabs/saucectl:latest
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      SAUCE_REGION: us-west-1
      STORAGE_ID: ${{ needs.retain-files.outputs.storage_id }}
      DOCKER_TAG: danielpatrickgraham/node:18 # TODO: Can be changed to just "node:18" when saucectl works without config file
    strategy:
      fail-fast: false
      matrix:
        entrypoint: [
          "sh -c '\
            curl -u $SAUCE_USERNAME:$SAUCE_ACCESS_KEY https://api.$SAUCE_REGION.saucelabs.com/v1/storage/download/$STORAGE_ID --output test-files.zip;\
            npm ci;\
            npm run test.saucelabs.us;\
          '"
        ]
    steps:
      - run: saucectl run

