name: Best Practices Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # Build the project as a Docker image and push it to Docker Hub
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    outputs:
      docker-tag: ${{ steps.meta.outputs.tags }}
      docker-slabels: ${{ steps.meta.outputs.labels }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/js-hosted-execution
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # Now run the tests. When Hosted Executor is ready, this should run a saucectl command to run
  # the tests from the previously created Docker image in the cloud
  run-tests:
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        DOCKER_TAG: ${{ needs.push_to_registry.outputs.docker-tag }}
      run: |
        echo ${{ needs.push_to_registry.outputs.docker-tag }}
        echo "TODO: run saucectl with Docker container ${{ secrets.DOCKER_USERNAME }}/js-hosted-execution:$DOCKER_TAG"
