apiVersion: v1alpha
kind: imagerunner
sauce:
  region: us-west-1
suites:
  - name: Desktop Tests
    image: $DOCKER_TAG
    imagePullAuth:
      user: hello
      token: hello
    entrypoint: $ENTRYPOINT
    env:
      SAUCE_REGION: $SAUCE_REGION
      STORAGE_ID: $STORAGE_ID
